name = "Packed"
author = "Encode42"
version = "4.1.0"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0358aee8886127fc9fc3b51d3b0fb671ec8f1ade18749a2c91a15cf035577b79"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"
