name = "Packed"
author = "Encode42"
version = "4.2.2"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a780662813c3d4260c3fe4cc37b28f8273992d46f047a9219c9289008deea479"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"
