name = "Packed"
author = "Encode42"
version = "4.1.0"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e09879529f6a76e1915a69c107f1d5b5ccbf4e093738c9af9d36d33578cf889e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"
