name = "Packed"
author = "Encode42"
version = "4.1.0"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83a8643e6f387add11498e2c26b70d0da210320cf03dab1c0f5ee3d40b9d58b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"
