name = "Packed"
author = "Encode42"
version = "5.8.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec276b5b316d5567504a03d9a9961166bb871a6854a7902137059a4f5f62c8f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
