name = "Packed"
author = "Encode42"
version = "4.0.0"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16e961f4eda43decbad49454610f92a438aedbd47b2ce224d7c6d0c83b586e84"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"
