name = "Packed"
author = "Encode42"
version = "6.0.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9b5a743dbff65ab10ba51483937a60dcee8205ff410ee8c04c90187736beb58"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
