name = "Packed"
author = "Encode42"
version = "5.3.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00451549e386028786476588b8d5974522df680836a005204ed614694e242e78"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
