name = "Packed"
author = "Encode42"
version = "6.0.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b768d6cf57120fee32538c1e8572f37edb3aa681e5ac2a59a73e36434f6f9404"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"
