name = "Packed"
author = "Encode42"
version = "4.5.1"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f86cf068ff90efd707931062c35b242ba0123dad5f10de9eeed5408d98860e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"
