name = "Packed"
author = "Encode42"
version = "4.5.1"
description = "Various visual, auditory, and improvement mods packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb521ddce953f12e7af6f88ba887ab2ad473429515b40f4c1bbbd31c27714f38"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"
