name = "Packed"
author = "Encode42"
version = "5.5.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8e9db73a69faf4a0b80bc93707e8f22fbef84b2a04f53013eaaa9f934deb185"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
