name = "Packed"
author = "Encode42"
version = "5.2.0"
description = "Vanilla-styled visual, auditory, and gameplay improvements packed into the client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf3dccddbd17104804bdffad218f3447a09fde33dbf3ee33788fc02c1352b199"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
